### ISSUE TITLE
Inovelli Blue Switch is discovered as Light

### ISSUE THREAD

**Issue by konistehrad** [chrivers/bifrost#17]
The [Inovelli Blue wallswitch](https://www.zigbee2mqtt.io/devices/VZM31-SN.html) is discovered as a light, probably owning to it's two-endpoint configuration to allow for advanced binding configuration. Unfortunately, it probably shouldn't be iterated as a light, though I'm not sure the best way to filter it out right now.

**Comment by chrivers** [comment]
Interesting. It looks like that wall switch has an LED light, and exposes it as a light (it even says so in your linked page)

What happens if you turn on the button from bifrost? Does the button light up? 😄

**Comment by konistehrad** [comment]
Yea, it's a weird one but I don't believe it's the built-in LED that's doing it. The device exposes two endpoints:

1. Endpoint 1 is there to provide OnOff and LevelControl inputs, which can optionally get shot out via:
2. Endpoint 2, which provides the output endpoints which basically send out bound commands from Endpoint 1 to bound devices.

In that regard, it does what you expect: sending an OFF command to the Inovelli on Endpoint 1 will send out the Off commands to anything bound via Endpoint 2. The onboard LED is controlled via a manufacturer specific cluster on Endpoint 1, and I don't imagine you're iterating manu clusters.

**Comment by chrivers** [comment]
Hm, that's a funny one.

According to the "expose" info from z2m, this "is" a light. It even says so right at the beginning of the page you linked:

```
light (state, brightness), ... 
```

Don't get me wrong, this is obviously not a light, at least in the classical sense.

But I'm not really sure what to look for, to detect that.

Do you have any idea what the light "expose" might be/mean/control?

**Comment by konistehrad** [comment]
I'd say anything with `genOnOff` Output clusters on any endpoint isn't a proper light. You can't just look for Output clusters, unfortunately, since `genOta` is technically an output cluster, but if it'll export On/Off commands, it probably isn't the light you're looking for.

**Comment by konistehrad** [comment]
I took a stab at this, but I'm very, very new to rust and still getting up to speed. Let me know if this makes sense for an updated `expose_light`:

```
    #[must_use]
    pub fn expose_light(&self) -> Option<&ExposeLight> {
        let has_on_off_output = self.endpoints.iter().find(|epmap| {
            epmap.1.clusters.output.iter().find(|cluster| {
                cluster.eq_ignore_ascii_case("genonoff")
            }).is_some()
        });
        if has_on_off_output.is_some() {
            return None;
        }
        
        self.exposes().iter().find_map(|exp| {
            if let Expose::Light(light) = exp {
                Some(light)
            } else {
                None
            }
        })
    }
```

**Comment by chrivers** [comment]
Thanks for the "stab" :D

I understand your code, and in general, that direction is probably viable.

However, I'm not sure if the specific heuristic proposed here is safe to use.

I checked my lights, and they wouldn't be affected by this, but it's kind of hard to guess what the implications will be.

For example, if we decide to blanket ban all devices with this endpoint structure, there's no recourse or workaround, if a user ever finds a device with this particular endpoint layout.

However, if we instead make it possible to e.g. blacklist devices based on, say, model id, manufacturer, etc, it would be reasonably easy for a user to ignore problematic devices, without ever putting any of them outside the realm of possibility.

**Comment by chrivers** [comment]
@konistehrad any idea what the exposed "light" feature means for this particular device?

Is there any chance it is related to the built-in LEDs?

It just seems really strange to me, that this switch exposes a "light". I would like to understand what is going on, before we take drastic action :)

**Comment by konistehrad** [comment]
I can confirm that it's not for the LEDs. The LEDs are controlled on the `manuSpecificInovelli` cluster on endpoint 1, not the `genOnOff` or `genLevelCtl`. It's definitely to allow values to flow from the device itself to one or many bound devices. The data flow is Endpoint 1 -> Endpoint 2 -> Bound Devices. Lights should only ever have Input clusters to allow control of their own values. I guess you're right now, I can't account for every light on the market given the sort of Wild West nature of the Zigbee ecosystem.

That said, I'd be happy to move this to a different facility.

**Comment by konistehrad** [comment]
The more I think on it, the more I think you're right: we shouldn't be trying to do anything too fancy here. There's a world where someone would want to control their Inovelli via Bifrost and do some kind of Zigbee messaging under the hood and we shouldn't be limiting that opportunity.

**Comment by chrivers** [comment]
> I can confirm that it's not for the LEDs. The LEDs are controlled on the `manuSpecificInovelli` cluster on endpoint 1, not the `genOnOff` or `genLevelCtl`. It's definitely to allow values to flow from the device itself to one or many bound devices. The data flow is Endpoint 1 -> Endpoint 2 -> Bound Devices. Lights should only ever have Input clusters to allow control of their own values. I guess you're right however, I can't account for every light on the market given the sort of Wild West nature of the Zigbee ecosystem.
> 
> That said, I'd be happy to move this to a different facility.

I realize I didn't read your explanation closely enough first time around - thanks for elaborating.

That's one of the more "spicy" devices out there :sweat_smile: 

I agree with your second comment - bifrost should *not* have a magic, always-on rule that removes a subset of devices from the users control, even if it might be convenient.

That said, a feature for ignoring devices based on certain criteria would solve this, and be more broadly useful. So let's move in that direction :+1:

**Comment by chrivers** [comment]
@konistehrad We agree that this kind of heuristic auto-blacklisting is not the way forward. So I'll close this issue :+1: 

Let me know if you want help with the blacklisting PR :)

**Comment by rohankapoorcom** [comment]
Maybe I'm missing something but it's a dimmer switch that can be connected to regular ceiling lights. In that case when you tell the switch to dim, it's actually dimming the ceiling lights (which are physically connected to it), that means it "is" the light as far as the smart home is controlled. In that case, I can think of use cases why I would Bifrost to be able to control it.

It can also control zigbee lights instead of hardwired lights, in which case it's likely not useful to control it via Bifrost (rather control the Zigbee lights/groups directly).

The light bar is not exposed as a separate light, it's only controlled via the configuration parameters.

I think either a denylist (ignore this light) or an allow list for Bifrost would make sense rather than trying to do something fancy and ignoring specific types of lights.
