### ISSUE TITLE
Event loop broke: unknown field `description`

### ISSUE THREAD

**Issue by andawi** [chrivers/bifrost#37]
I recently discovered this project and am really excited to give it a try! :) Many thanks for creating it!

After setting up the latest version (Sep 7), I ran into an error that continuously loops without further success.

```rust
ERROR bifrost::z2m                   > [server1] Event loop broke: unknown field `description`, expected one of `date_code`, `definition`, `disabled`, `endpoints`, `friendly_name`, `ieee_address`, `interview_completed`, `interviewing`, `manufacturer`, `model_id`, `network_address`, `power_source`, `software_build_id`, `supported`, `type` at line 1 column 177009
```

The complete log (since it exceeds the character limit of one post)
[error_log_2024-09-13T12:50:45.txt](https://github.com/user-attachments/files/16998504/error_log_2024-09-13T12.50.45.txt)

Not sure if the provided log is sufficient for further analysis. I'm happy to help and provide additional details, logs, etc.

**Comment by chrivers** [comment]
@andawi please try again - let me know how it goes :)

**Comment by andawi** [comment]
Bugfix confirmed - many thanks!
