### ISSUE TITLE
deprecated library.

### ISSUE THREAD

**Issue by hendriksen-mark** [chrivers/bifrost#40]
during compiling in the logs i noticed a deprecated library.
`Compiling serde_yaml v0.9.34+deprecated`
`serde_yaml` is as of march 25 2024 no longer maintained.
https://github.com/dtolnay/serde-yaml

**Comment by chrivers** [comment]
Good catch - I'm going to switch over to https://github.com/sebastienrousseau/serde_yml, which has recently gained popularity.

It's a maintained fork, and it looks to be a drop-in replacement.
