### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by joeblack2k** [chrivers/bifrost#6]
Thanks a bunch for making this! My wife and I are thrilled to finally be able to use our Phillips Hue app again. We have a bunch of lights, and they’re all in Z2M, except for two that are Nanoleaf. Those are in Home Assistant.

So, here’s my next request, and I know it might be a bit of a long shot, but I was wondering if it’s planned to add lights from Home Assistant or maybe we could custom export Home Assistant lights to MQTT like /bifrost/lights/state. That would be amazing!

**Comment by chrivers** [comment]
Thank you for trying Bifrost! I'm really happy to hear it works well for you :)

How did the installation go? Was it relatively easy, or were there any surprises?


The nanoleaf lights, what kind of lights are they? Are they zigbee-based? Or how do you connect to them?

With the exciting feedback, it does seem like integrating home assistant lights would be an interesting project - if I can find more spare time 😅

But "exporting" lights is a bit more tricky, since bifrost would need to know who to contact to request updates (on/off, brightness, color, recall/create/delete scene, etc).

**Comment by joeblack2k** [comment]
following your brief install guide i'm here:

installing on dietpi clean vm on a synology NAS

you also need "sudo apt-get install build-essential"

the sample config states /cert/cert but the folder cannot be created by bifrost (fix?) so you need to make the folder yourself

now i have one error lef:
<img width="1285" alt="Screenshot 2024-08-23 at 12 50 41" src="https://github.com/user-attachments/assets/4a6e2ef6-526a-4898-bda2-63d5368251a4">

somehow Hue and Hue Essentials app cannot find the bridge..

**Comment by joeblack2k** [comment]
> The nanoleaf lights, what kind of lights are they? Are they zigbee-based? Or how do you connect to them?

Unfortunately, the Nanoleaf lights in use are WiFi, Matter, and HomeKit compatible, with Home Assistant connecting to them via Nanoleaf's API.

**Comment by joeblack2k** [comment]
I don't see any lights and notice many rooms are created based on my z2m groups. 

Maybe it's better to either start fresh or only import groups that begin with 'bifrost_' like 'bifrost_livingroom'.


![image](https://github.com/user-attachments/assets/50d4629e-0158-4283-94eb-21b317372657)

**Comment by chrivers** [comment]
By the way, see [the config reference](https://github.com/chrivers/bifrost/blob/master/doc/config-reference.md) (at the bottom) for a way to choose a nicer name + icon for your rooms.

If you do change the "rooms" config option, you'll want to

  1) stop bifrost
  2) delete `state.yaml`
  3) start bifrost

This will force a full refresh from z2m, which will map your rooms with names and icons.

Yes, the room mapping is a bit rough at the moment, but it's a work in progress.. ;)

**Comment by joeblack2k** [comment]
> I realize the documentation on this is lacking at the moment, but you're not supposed to create rooms yourself. It's 
> supposed to be rejected, but I might have accidentally left it in.

oh i meant on Z2M side.. the current groups are used for automations, not all groups are needed in the hue app so if you can differentiate you can filter on bifrost.. creating bifrost_kitchen on z2m so you know thats going to be in the hue app

i will get some logs now!

**Comment by joeblack2k** [comment]
Mail sent!

**Comment by chrivers** [comment]
I figured out the problem! It was a few things, combined:

 1) A small api difference between z2m versions (I run 1.39.1)
 2) A type of device information I haven't seen before ("ExposeLock" in the src)
 3) A few fields that I had modelled poorly (optional fields assumed to be required, etc)

I have an experimental branch with those fixes, here:

  https://github.com/chrivers/bifrost/tree/chrivers/z2m-fixes

Can you give it a try?

**Comment by maskaz** [comment]
Now i cannot compile.

I had removed everything, installed Cargo (Version 1.75.0, OS: Ubuntu 24.04 LTS)

Error:
Compiling bifrost v0.1.0 (/home/maskaz/.cargo/git/checkouts/bifrost-5a426757687fce85/2a2873b)
error[E0432]: unresolved import `std::hash::DefaultHasher`
 --> src/hue/api/resource.rs:2:17
  |
2 | use std::hash::{DefaultHasher, Hash, Hasher};
  |                 ^^^^^^^^^^^^^ no `DefaultHasher` in `hash`
  |
  = help: consider importing this struct instead:
          std::collections::hash_map::DefaultHasher

warning: unused import: `Hasher`
 --> src/hue/api/resource.rs:2:38
  |
2 | use std::hash::{DefaultHasher, Hash, Hasher};
  |                                      ^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

**Comment by chrivers** [comment]
@maskaz I'd be happy to help you, but please don't put comments on unrelated, closed issues.

Let's continue in #3
