### ISSUE TITLE
Web Server Hardcoded to Bind Only on Ports 80 and 443 (i.e., No Arbitrary Ports / Support for Reverse Proxies)

### ISSUE THREAD

**Issue by medelman17** [chrivers/bifrost#9]
Currently, the `bifrost` web server is hardcoded such that it attempts to bind to both to ports 80 and 443 on whatever ip address is supplied by the user via the `config.yaml` file. There appears to be no way around this constraint at present (e.g., setting a BIFROST_PORT environment variable, etc). This is fairly pushy behavior and likely not extensible in the long run; especially, now, that support for `docker` is being introduced. 

It would likely behoove the project to adopt, sooner than later, non-standard port defaults for http and https. Typical self-host/homelabber `docker` use cases, where metric tons of services are ran alongside each other and reverse-proxies are king, are essentially blocked out of the gate as it stands. But, even where one would run `bifrost` as a system service on a standalone VPS/VM, the constraint will, in all likelihood, catch up to users real quick, limiting the use and appeal of the software.

I'm happy to take a shot at putting together a PR for this if we can settle on the approach in advance. :-)

**Comment by chrivers** [comment]
Hi - welcome to bifrost :)

It's a good point, and pretty easy to add.

Sorry, I missed that you wanted to help. I didn't mean to take that option away from you, but now it's implemented 😅

But maybe you can help test it? I've updated the documentation accordingly (look for `http_port` + `https_port` in the config reference)

**Comment by hugo-vrijswijk** [comment]
@chrivers I'm using different ports for Bifrost as 80 and 443 are in use already on my machine. But the Hue app is unable to find any bridge when setting up the app. Is there a way around this? I'm not sure how to continue

**Comment by chrivers** [comment]
@hugo-vrijswijk I've created a new issue to track this: https://github.com/chrivers/bifrost/issues/53

Let's continue the discussion there, thank you.
